# Generated by Django 3.1.4 on 2021-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='accept_status',
            field=models.BooleanField(default=False),
        ),
    ]
